---
title: "Website building (1)"
description: |
  List of tools for creating a static website.
author:
  - name: Ben Welman
date: 09-09-2018
preview: preview.png
citation: false
categories:
  - markdown
  - hugo
output:
  distill::distill_article:
    self_contained: true
---

This website is a so-called static website that is composed by a generator from a number of source documents.

## Tools

1.  [Blogdown](https://bookdown.org/yihui/blogdown/), an R package for creating static websites with *Rmarkdown*.
2.  [RStudio](https://www.rstudio.com/), an integrated development environment for the language *R*.
3.  [Hugo](https://gohugo.io/), a popular open-source static website generator.
4.  [Learn theme](https://themes.gohugo.io/hugo-theme-learn/), a theme for *Hugo*.
5.  [Git](https://git-scm.com/), a version management system.
6.  [GitHub](https://github.com/), a popular hosting service for *Git* repositories.
7.  [Markdown](https://daringfireball.net/projects/markdown/) and [RMarkdown](https://rmarkdown.rstudio.com/) as markup languages for the source documents.
8.  [MathJax](https://www.mathjax.org/), a javascript engine for mathematical expressions in browsers.
9.  [Google Analytics](https://analytics.google.com), for analyzing  the use of the website.
10. [Sourcetree](https://www.sourcetreeapp.com/), a free Git GUI for Windows and Mac.

## Method

R, RStudio and Git were already installed. A GitHub and Google Analytics account was already there. In general, the method was

1.  Installing package Blogdown through RStudio.
2.  Creating a new RStudio project for this website, based on Hugo theme Learn.
3.  Changed the project folder in a Git repository.
4.  Made various adjustments for structure and layout.
5.  New content created.
6.  After testing, build the website and push it to the server.

In a next article some details will be discussed in more detail.
